spring:
  application:
    name: Bondoudou Store
  datasource:
    url: ${BONDOUDOU_DB_URL}
    username: ${BONDOUDOU_DB_USER}
    password: ${BONDOUDOU_DB_PASSWORD}
    driverClassName: org.h2.Driver
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: none
      id.db_structure_naming_strategy: legacy
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true

#http://localhost:8080/h2-console

logging:
  level:
    edu.sorbonne: DEBUG